# NOME DO NOSSO PROJETO
spring.application.name=projeto-spring-boot-com-postgres

# URL DEFINITIVA COM PORTA ALTERNATIVA E REMOÇÃO DE VALIDAÇÃO DE CERTIFICADO INTERCEPTADO
spring.datasource.url=jdbc:postgresql://ep-lively-sea-acsb1gk1-pooler.sa-east-1.aws.neon.tech:443/neondb?ssl=true&sslfactory=org.postgresql.ssl.NonValidatingFactory
spring.datasource.driver-class-name=org.postgresql.Driver

# CREDENCIAIS DO BANCO
spring.datasource.username=neondb_owner
spring.datasource.password=npg_BC5JdX4jVaOR

# HIBERNATE E DIALETO
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
